services:
  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
     - 80:80
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii
    depends_on:
      - php
  php:
    container_name: yii_php
    build: ./images/php81fpm
    volumes:
      - ./www:/var/www
      - ./php.ini:/user/local/etc/php/conf.d/php.ini
    networks:
      - yii
    depends_on:
      - mysql
  mysql:
    container_name: yii_mysql
    image: mysql:latest
    ports:
      - 33060:3306
    volumes:
      - ./www:/var/www
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_USER=yii
      - MYSQL_PASSWORD=yii
      - MYSQL_ROOT_PASSWORD=yii
      - MYSQL_DATABASE=yii
    command: ["--mysql-native-password=ON"]
    networks:
      - yii 


networks:
  yii:

volumes:
  db: